# Generated by Django 4.1.3 on 2022-12-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_foods_rate_alter_foods_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='food_type',
            field=models.CharField(default='drink', max_length=10, verbose_name='نوع خوراکی'),
        ),
    ]
