# Generated by Django 4.1.3 on 2022-12-04 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_foods_food_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foods',
            old_name='food_type',
            new_name='type_food',
        ),
    ]
