# Generated by Django 4.1.3 on 2022-12-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_rename_food_type_foods_type_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='type_food',
            field=models.CharField(choices=[('drinks', 'نوشیدنی'), ('dinner', 'صبحانه'), ('lunch', 'غذای اصلی')], default='drink', max_length=10, verbose_name='نوع خوراکی'),
        ),
    ]
