# Generated by Django 4.1.3 on 2022-12-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=1, upload_to='blogsImg/', verbose_name='تصویر'),
            preserve_default=False,
        ),
    ]
